### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by Catsvilles** [sebpiq/node-audionodes-sox#2]
Hi, could you please add some more info in README file, preferably with a few usage examples. I spent quite a time installing it as it requires packages that are not even specified in package.json file. Thank you!

**Comment by sebpiq-kialo** [comment]
Hi! This was designed to work with the [node implementation of web audio API](https://github.com/audiojs/web-audio-api) which I wrote many years ago and am not maintaining anymore. It's probably not working anymore, but you should be able to fix it by just looking at the code! Good luck ;)

**Comment by sebpiq** [comment]
Hi @Catsvilles ! This was designed to work with the [node implementation of web audio API](https://github.com/audiojs/web-audio-api) which I wrote many years ago and am not maintaining anymore (@audiojs took over). It's probably not working anymore, but you should be able to fix it by just looking at the code! Good luck ;)

**Comment by Catsvilles** [comment]
@sebpiq Thanks for getting back to me! I just like the idea of turning Sox processed audio files to AudioBuffer. What I'm trying to achieve is adding audio effects to a file and somehow passing it to the frontend where I'm using Web Audio to play it. Will play around with this and see what will happen :)
